version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: gonimbus_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gonimbus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgresql/data

volumes:
 postgres_data: